- docker-compose.dev.yml
- docker-compose.stable.yml
- tests/docker-compose.test.yml
Found a nice trick to only run api when db is ready
> fix: run api after db

- app-ui/src/App.scss
- app-ui/src/lib/traceview/line.tsx
Trello: https://trello.com/c/o7VOdJSD/190-change-purple-feedback-annotation-to-red-green
Make thumb up/down be coloured green/red instead of purple:
https://github.com/user-attachments/assets/7f13c3c1-83e6-46bb-991f-9395118ce94a
> Change feedback colouring

- .gitignore
- app-api/models/queries.py
- app-api/routes/dataset.py
- app-ui/src/App.scss
- app-ui/src/Dataset.tsx
- app-ui/src/NotFound.tsx
- app-ui/src/RemoteResource.tsx
- app-ui/src/Routes.tsx
- app-ui/src/Traces.tsx
- app-ui/src/User.tsx
- tests/test-ui-api/test_dataset.py
Adding better 404/401 pages for:
* `/u/valid_user/invalid_or_private_dataset/`
* `/u/valid_or_invalid_user/invalid_or_private_dataset/`
* `/u/valid_or_invalid_user/invalid_or_private_dataset/t/0`
* `/u/invalid_user`
* `/trace/invalid_trace`
* `/invalid_route`
> fix: better error pages

- app-ui/src/Traces.tsx
- tests/test-ui/test_basic.py
Fix issue where search can get stuck: https://trello.com/c/NxAL7xXc/178-search-sometimes-bugs-out-on-traces
By request, also added explicit confirmation for running searches. Instead of eagerly searching with potentially partial strings in the search box, the user now has to either click the search icon or press enter to initiate a search.
> Require explicit confirmation on search 

- app-api/routes/benchmark.py
- app-api/routes/dataset.py
- app-ui/src/AnnotationAugmentedTraceView.jsx
- app-ui/src/App.scss
- app-ui/src/Datasets.tsx
- app-ui/src/Traces.tsx
- app-ui/src/components/EmptyDataset.tsx
- tests/test-ui-api/test_dataset.py
- tests/test-ui/test_basic.py
* Contains changes to the upload API where now we can upload traces to an existing empty dataset. 
* If the user tries to upload traces via file upload to a non empty dataset, we throw a 400. We can relax this requirement as a follow-up. The importer has the starting index set to 0.
Task: https://trello.com/c/gNbkmvWr/156-tweaks-needed-to-the-empty-dataset-view
> Improve the empty dataset view to allow users to upload a file with the traces

- tests/test-ui/test_basic.py
Add `await page.wait_for_url()` to wait for the page redirect after deleting the dataset.
> Fix test failure for test_create_empty_dataset_and_then_upload_file and test_create_delete_dataset.

- app-ui/src/AnnotationAugmentedTraceView.jsx
- app-ui/src/Traces.tsx
Task: https://trello.com/c/uKWkWKSc/175-sharing-a-trace-from-a-public-dataset-should-not-have-the-privacy-share-window-show-up
> Hide the share button on public datasets not owned by the user.

- app-api/routes/benchmark.py
- tests/test-ui-api/test_benchmark.py
Task: https://trello.com/c/oR5x7VuS/197-make-benchmarkget-benchmarkname-leaderboard-api-public
> Remove Authorization header check from the benchmark leaderboard API and rewrite it to move the Python logic into the SQL query

- app-ui/src/App.scss
- app-ui/src/Layout.tsx
- app-ui/src/lib/traceview/TraceView.scss
- hide log out when run in local
- fix updown feedback button in json.table
- for edge case with long key string, the cell width is fixed and text is breaked, showed in next line
trello task: https://trello.com/c/ozeWzTFs
screenshot:
> Fix updown feedback button

- app-ui/public/theme/css/invariant.scss
- app-ui/src/App.scss
- app-ui/src/Explorer.scss
- app-ui/src/Home.scss
- app-ui/src/invariant.scss
- app-ui/src/lib/Metadata.scss
Trello task: https://trello.com/c/fNjezOMi/209-fix-sass-warnings-showing-up-on-ci
Fixed using this example: https://github.com/jekyll/jekyll/issues/9686#issuecomment-2373992357 and https://github.com/nolimits4web/swiper/issues/7771#issuecomment-2433515054
> Fix SASS Deprecation warnings.

- app-ui/src/lib/annotations_parser.ts
- app-ui/src/lib/traceview/highlights.ts
- app-ui/src/lib/traceview/plugins/image-viewer.scss
- app-ui/src/lib/traceview/plugins/image-viewer.tsx
Adds bounding box highlights to images:
The example uses the InvariantImage OCR functionality (only function that produces bboxes at the moment) to find all instances of `invariant` in the image. 
Currently:
- The colour of a bbox defaults to 'invariant purple' when no source (i.e., test pass/fail details) is provided in the annotation, and is otherwise green/red depending on the source.
- The bboxes have no tool tips.
- Are shown when the image is fullscreen as well.
- The image the bboxes are on is still highlighted seperately. This is to show the result of other assertions that may not produce bboxes.
Please see related PR: https://github.com/invariantlabs-ai/invariant/pull/37
> Add bounding box highlights for images

- app-api/routes/dataset.py
- tests/test-ui-api/test_dataset.py
A `dataset_name` can be the same across users but the combination of a `dataset_name` and a `user` is unique. Both the id (UUID) and the username (string) of a user are unique.
- Updates to the dataset metadata are permitted **only by the owner** of the dataset.  
- If a caller who **does not own** the dataset attempts to update it, the API returns a **404 Not Found** during the dataset lookup.
---
- A new query parameter called **`owner_username`** has been introduced.  
- **If  `owner_username` is not passed**: 
- The caller `user_id` is used for the dataset lookup. If a dataset of that name is found, its metadata is returned **regardless of whether it is public or private** else we return a **404 Not Found**.
- **If `owner_username` is passed and it matches the caller's user:**  
- The …
> Update the get and update dataset metadata APIs.

- app-api/database/database_manager.py
- app-api/database/env.py
- app-api/models/datasets_and_traces.py
- tests/test-ui/test_basic.py
Also cache the resultant engine client so that it is not re-created for each query.
> Use pool_size while calling sqlalchemy.create_engine. 

- app-api/routes/dataset.py
- app-api/routes/dataset_metadata.py
- tests/test-ui-api/test_dataset.py
This PR refactors dataset metadata validation such that it lives in a separate file and it is much easier to add new metadta fields.
Most importantly, the following piece of code now configures what we allow as dataset metadata:
```python
allowed_field = [
TestReportField(),
PrimitiveMetadataField('benchmark', str),
PrimitiveMetadataField('name', str),
PrimitiveMetadataField('accuracy', (int, float)),
PrimitiveMetadataField('policies', list, include_in_response=False)
]
```
This should not change the behavior compared to before (waiting for tests to complete for this).
> Refactor Dataset Metadata Validation so that we can add more fields more easily

- app-api/models/queries.py
- app-ui/src/lib/traceview/TraceView.scss
- app-ui/src/lib/traceview/plugins/code-highlighter.tsx
- app-ui/src/lib/traceview/plugins/image-viewer.tsx
- app-ui/src/lib/traceview/traceview.tsx
When a JSON array is present in a message, we can now render each element in the array independently. This allows us to do mixed content rendering, like having an image and a piece of text in the same message in a trace.
We assume that elements in the array have a `type` field, and if not, we render them as regular JSON data.
> Mixed content rendering for JSON arrays in messages

- app-api/models/datasets_and_traces.py
- app-api/models/importers.py
- app-api/models/queries.py
- app-api/routes/apikeys.py
- app-api/routes/auth.py
- app-api/routes/dataset.py
- app-api/routes/dataset_metadata.py
- app-api/routes/push.py
- app-api/routes/trace.py
- app-api/routes/user.py
- app-ui/server/auth.py
Cleanup on user authentication backend. Now an `user_id` is always retuned. For endpoint that don't require authentication it's None.
If more informations are needed (username, email, ...), they can be found under `request.state.userinfo`.
> fix: type hinting for user authentication

- app-ui/src/lib/traceview/traceview.tsx
* Added a badge next to tool call outputs to display the tool name. 
* When tool output content was not of type string or object, we were not rendering the message correctly. Made it better. 
Tested with this trace: 
```
traces = [
[
{
"role": "system",
"content": "This the system instruction. Use the function call.",
},
{
"role": "user",
"content": [
{"type": "text", "text": "Turn the lights down to a romantic level"}
],
},
{
"role": "assistant",
"tool_calls": [
{
"type": "function",
"function": {
"name": "set_light_values",
"arguments": {"brightness": 20, "color_temp": "warm"},
},
}
],
},
{
"role": "tool",
"tool_name": "set_light_values",
"content": 176258992,
},
{
"role": "tool",
"tool_name": "set_light_values",
"content": [
1,
2,
3,
"hello_world",
{"a": "b", "c": [1, 2, "3"]},
[1, 2, …
```
> Add badge for tool_name when message.role is tool. Also render tool outputs correctly for types other than string and objects.

- app-api/models/queries.py
- app-api/util/util.py
- app-ui/src/lib/traceview/traceview.tsx
Tested using these snippets via UI upload and push traces API: 
* https://gist.github.com/hemang1729/cc68fe1f1962d32da00917ddb02cb175 -> image directly in content
* https://gist.github.com/hemang1729/f03eb1b9f5313e9776606da254157273 -> image in content list object of type `image_url`.
This change has to be backward compatible since there are traces in our production database where the image base64 is stored in the postgres column.
> Handle image upload and download when message content is a list of objects and some of these contains images.

- app-ui/src/pages/traces/Guardrails.tsx
This PR simplifies the guardrail UI by combining the enabled/paused status with the action selection. Instead of having a separate section for enabled/paused status, users can now select from three options at the same level:
- Block Agent (enabled=true, action=block)
- Log Failure (enabled=true, action=log)
- Paused (enabled=false, action=log)
Changes:
- Combined enabled/paused status with action selection
- Added Paused option at same level as Block and Log
- Removed redundant LIVE badge
- Maintained internal action and enabled state based on selection
This change makes the UI more intuitive and reduces the number of decisions users need to make when configuring guardrails.
> Unify guardrail actions and status into single selection

- app-api/database/versions/83097c7e026b_migrate_dataset_level_trace_index_to_.py
- app-api/models/importers.py
- app-api/routes/dataset.py
- app-api/routes/push.py
- app-api/routes/trace.py
- tests/test-sdk/test_push_trace.py
- tests/test-ui-api/test_import_export.py
- tests/test-ui/test_basic.py
* For a snippet, the index is 0, and the dataset_id column is NULL in the trace row.
* The PostgreSQL sequence for the index starts at 0 for an empty dataset. As we push traces into it, the index increases by 1 each time. The first trace pushed has an index of 0, the second one has an index of 1, and so on.
* If we upload a dataset file containing indices, we verify that each trace has an index field and that all indices are unique. In this case, a PostgreSQL sequence is not created, and the provided indices are used as is. Later, if we push a new trace to this dataset, a PostgreSQL sequence is created, starting at max(current indices for this dataset) + 1.
* For dataset file uploads, if no index exists in the file, we simply initialize a sequence starting from 0. Previously, this was set …
> Add alembic migration to add a postgres sequence for the trace index column.

- app-api/models/queries.py
- app-api/routes/dataset.py
- app-ui/src/pages/home/Home.tsx
- app-ui/src/pages/user/DatasetList.tsx
- app-ui/src/styles/App.scss
- Modified dataset queries to join with Trace table and order by latest trace time
- Updated dataset_to_json to include latest_trace_time
- Added fallback to dataset creation time when no traces exist
> Sort datasets by latest trace time instead of creation time

- app-api/models/queries.py
- app-api/routes/dataset.py
- app-api/routes/jobs.py
- app-api/routes/trace.py
- app-ui/src/lib/annotations_parser.ts
- app-ui/src/lib/traceview/TraceView.scss
- app-ui/src/lib/traceview/highlights.ts
- app-ui/src/lib/traceview/traceview.tsx
- app-ui/src/pages/traces/Analyzer.tsx
- app-ui/src/pages/traces/AnnotationAugmentedTraceView.jsx
- app-ui/src/pages/traces/Traces.tsx
- app-ui/src/pages/traces/ViewOptions.tsx
- app-ui/src/styles/App.scss
- tests/test-ui/test_filter_search.py
* now analyzer annotations are not anymore batched. Each annotation is a record in the Annotation field.
* better labels on the left
* In the view-options menu, possiblity to enable or disable view of badges in the left sidebar
https://github.com/user-attachments/assets/1e935b05-9fd9-4dae-a755-e2fa53a69278
> Split analyzer model annotations

- app-api/routes/trace.py
- tests/test-ui-api/test_trace.py
We don't need to update addresses on the annotations for the new messages. This will not work correctly with concurrent append messages calls when we also add annotations - we intend to fix that in the future by using some sort of a message level id instead of index to connect an annotation to a message.
This will work with the current MCP gateway stdio implementation since guardrail checking service will give us annotations for both the older messages in the trace and the newer messages with the correct addresses. There will not be concurrent calls to the same trace in this case.
> Fix append messages API so that it accepts annotations for existing messages too.

- app-api/routes/dataset/traces.py
The downloaded files should be jsonl because the analyzer model requires datasets to be jsonl files.
> change download-analyzer file extension from json to jsonl
